#!/bin/bash

echo "🔧 Fixing CORS Error - Adding Frontend URL to Railway"
echo "=================================================="

echo "📝 To fix the CORS error, you need to:"
echo ""
echo "1. Go to Railway Dashboard: https://railway.app"
echo "2. Open your MetroUni backend project"
echo "3. Click 'Variables' tab"
echo "4. Add this environment variable:"
echo ""
echo "   Variable Name: ALLOWED_ORIGINS"
echo "   Variable Value: YOUR_FRONTEND_URL,http://localhost:5173"
echo ""
echo "   Replace YOUR_FRONTEND_URL with your actual frontend URL"
echo "   Examples:"
echo "   - Netlify: https://metriuni-12345.netlify.app"
echo "   - Vercel: https://metriuni-abcdef.vercel.app"
echo ""
echo "5. Railway will automatically restart your backend"
echo "6. Try logging in again after 1-2 minutes"
echo ""
echo "🎯 What's your frontend URL?"
