[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://web-production-7bab5.up.railway.app"
  VITE_SOCKET_URL = "https://web-production-7bab5.up.railway.app"
  VITE_APP_NAME = "MetroUni"
