# Railway Nixpacks Configuration for MetroUni
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd backend && npm ci",
  "cd frontend && npm ci && npm run build"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
