# Railway Nixpacks Configuration for MetroUni
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install && npm run build"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
