services:
  - type: web
    name: metriuni-backend
    env: node
    plan: free
    runtime: node
    buildCommand: cd backend && npm ci --only=production
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: UPLOAD_MAX_SIZE
        value: 10485760
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
